#!/bin/bash

su laradock -c "curl https://raw.githubusercontent.com/creationix/nvm/v0.15.0/install.sh | bash; . ~/.nvm/nvm.sh; nvm install 8.2.1; npm install; npm install --global gulp-cli; gulp svgSpriteBuild; npm run dev"
# curl https://raw.githubusercontent.com/creationix/nvm/v0.15.0/install.sh | bash
# # . ~/.nvm/nvm.sh
# nvm install 8.2.1
# npm install
# npm install --global gulp-cli
# gulp svgSpriteBuild
# npm run dev